### ISSUE TITLE
How long for Pre_Process?

### ISSUE THREAD

**Issue by Erinico233** [shalgilab/DoGFinder#11]
Hello, I'd like to know approximately how long the 'Pre_Process' step takes for a single BAM file with 30 threads. My process has been running for three days, but no files have been generated. I'm not sure if this step really takes a long time or if there's a problem with my execution. I'm looking forward to your response. Thank you.

**Comment by Erinico233** [comment]
Thanks, solved. About 5mins.

**Comment by SevenTea7** [comment]
Hello, I encountered some problems when installing DoGFinder. Could you please give me some help? Thank you very much
I ran into "/bin/sh: 1: infer_experiment.py: not found" when running "python setup.py test"
"And can not generate bed file, please help me, thank you.
